import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "s.p.Audio",
  description: "Generated by create next app",
};
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});


import Header from '@/components/Header';
import Footer from '@/components/Footer';
import ClientWrapper from '@/components/ClientWrapper';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} font-sans antialiased flex flex-col min-h-screen`}
      >
        <ClientWrapper>
          <Header />
          <main className="flex-grow">{children}
            <Toaster position="top-right" /></main>
          <Footer />
        </ClientWrapper>
      </body>
    </html>
  );
}
